const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const loader = fs.readFileSync(path.join(root, 'frontend/js/modules/org-departments.js'), 'utf8');
const departmentCore = fs.readFileSync(path.join(root, 'frontend/js/modules/org-departments-core.js'), 'utf8');
const bridge = fs.readFileSync(path.join(root, 'frontend/js/modules/agent-organization.js'), 'utf8');
const agents = fs.readFileSync(path.join(root, 'frontend/js/modules/agents.js'), 'utf8');
const safeWrite = fs.readFileSync(path.join(root, 'backend/routes/agents_safe_write.js'), 'utf8');
const integrityRoute = fs.readFileSync(path.join(root, 'backend/routes/organization_integrity_safe.js'), 'utf8');
const service = fs.readFileSync(path.join(root, 'backend/services/organization_assignment.js'), 'utf8');
const server = fs.readFileSync(path.join(root, 'backend/server.js'), 'utf8');

assert(loader.includes('/js/modules/org-departments-core.js'));
assert(loader.includes('/js/modules/agent-organization.js'));
assert(!loader.includes('display: none !important'));
assert(departmentCore.includes('orgNewDepartement'));
assert(bridge.includes("request('/org/departements')"));
assert(bridge.includes("request('/org/postes')"));
assert(bridge.includes("request('/org/sites')"));
assert(bridge.includes("request('/org/arbre')"));
assert(bridge.includes('ag-departement-select'));
assert(bridge.includes('ag-superieur-select'));
assert(bridge.includes('applyDepartmentManager'));
assert(bridge.includes('setSupervisorLocked(applied)'));
assert(!bridge.includes('Responsable hiérarchique appliqué automatiquement :'));
assert(!bridge.includes("request(`/org/${result.agentId}/superieur`"));
assert(bridge.includes('Supérieur hiérarchique synchronisé avec le département.'));
assert(agents.includes("departement: rawValue('ag-departement')"));
assert(agents.includes("superieur_hierarchique: rawValue('ag-superieur')"));
assert(safeWrite.includes("require('../services/organization_assignment')"));
assert(safeWrite.includes('organizationSvc.resolveAgentAssignment'));
assert(integrityRoute.includes('organizationSvc.synchronizeDepartmentManager'));
assert(integrityRoute.includes('organizationSvc.assertDepartmentCanDeactivate'));
assert(integrityRoute.includes('organizationSvc.assertSupervisorChange'));
assert(service.includes('createsCycleFromMap'));
assert(service.includes('DEPARTMENT_IN_USE'));
assert(server.includes("require('./routes/organization_integrity_safe')"));
assert(server.indexOf('organizationIntegrityRouter') < server.indexOf("orgRouter);"));

console.log('OK - centralized organization integrity and clean UI');
