-- Pointeuse industrielle V3 : événements immuables, planning, anomalies, corrections et clôture.

CREATE TABLE pointeuse_events (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  employe_id INT NOT NULL,
  event_type ENUM('clock_in','break_start','break_end','clock_out') NOT NULL,
  occurred_at_utc DATETIME(3) NOT NULL,
  local_date DATE NOT NULL,
  local_time TIME NOT NULL,
  timezone_name VARCHAR(64) NOT NULL DEFAULT 'Africa/Brazzaville',
  utc_offset_minutes SMALLINT NOT NULL DEFAULT 60,
  source ENUM('web','mobile','kiosk','badge','import','rh') NOT NULL DEFAULT 'web',
  mode ENUM('bureau','teletravail','terrain') NOT NULL DEFAULT 'bureau',
  site_code VARCHAR(64) NULL,
  device_id VARCHAR(128) NULL,
  session_id VARCHAR(128) NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  ip_address VARCHAR(45) NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  precision_gps DECIMAL(10,2) NULL,
  hors_perimetre TINYINT(1) NOT NULL DEFAULT 0,
  payload_json JSON NULL,
  created_by INT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_pointeuse_event_idempotency (employe_id, idempotency_key),
  KEY idx_pointeuse_events_employee_time (employe_id, occurred_at_utc),
  KEY idx_pointeuse_events_local_date (local_date),
  KEY idx_pointeuse_events_type (event_type),
  CONSTRAINT fk_pointeuse_events_employe FOREIGN KEY (employe_id) REFERENCES employes(id),
  CONSTRAINT fk_pointeuse_events_user FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE pointeuse_work_schedules (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(64) NOT NULL,
  libelle VARCHAR(160) NOT NULL,
  timezone_name VARCHAR(64) NOT NULL DEFAULT 'Africa/Brazzaville',
  heure_debut TIME NOT NULL,
  heure_fin TIME NOT NULL,
  pause_minutes INT NOT NULL DEFAULT 0,
  tolerance_retard_minutes INT NOT NULL DEFAULT 15,
  tolerance_depart_minutes INT NOT NULL DEFAULT 0,
  nuit_traverse_minuit TINYINT(1) NOT NULL DEFAULT 0,
  actif TINYINT(1) NOT NULL DEFAULT 1,
  created_by INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_pointeuse_schedule_code (code),
  CONSTRAINT fk_pointeuse_schedule_user FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE pointeuse_schedule_assignments (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  employe_id INT NOT NULL,
  schedule_id INT NOT NULL,
  date_debut DATE NOT NULL,
  date_fin DATE NULL,
  jours_semaine VARCHAR(32) NOT NULL DEFAULT '1,2,3,4,5',
  site_code VARCHAR(64) NULL,
  mode_autorise ENUM('bureau','teletravail','terrain','hybride') NOT NULL DEFAULT 'bureau',
  created_by INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_pointeuse_assign_employee_dates (employe_id, date_debut, date_fin),
  CONSTRAINT fk_pointeuse_assign_employe FOREIGN KEY (employe_id) REFERENCES employes(id),
  CONSTRAINT fk_pointeuse_assign_schedule FOREIGN KEY (schedule_id) REFERENCES pointeuse_work_schedules(id),
  CONSTRAINT fk_pointeuse_assign_user FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE pointeuse_daily_summaries (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  employe_id INT NOT NULL,
  work_date DATE NOT NULL,
  schedule_id INT NULL,
  first_in_utc DATETIME(3) NULL,
  last_out_utc DATETIME(3) NULL,
  worked_minutes INT NOT NULL DEFAULT 0,
  break_minutes INT NOT NULL DEFAULT 0,
  late_minutes INT NOT NULL DEFAULT 0,
  early_leave_minutes INT NOT NULL DEFAULT 0,
  overtime_minutes INT NOT NULL DEFAULT 0,
  night_minutes INT NOT NULL DEFAULT 0,
  status ENUM('open','calculated','exception','approved','closed') NOT NULL DEFAULT 'open',
  anomaly_count INT NOT NULL DEFAULT 0,
  calc_version VARCHAR(32) NOT NULL DEFAULT 'v3.1',
  calculated_at DATETIME NULL,
  approved_by INT NULL,
  approved_at DATETIME NULL,
  closed_at DATETIME NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_pointeuse_daily_employee_date (employe_id, work_date),
  KEY idx_pointeuse_daily_status (status, work_date),
  CONSTRAINT fk_pointeuse_daily_employe FOREIGN KEY (employe_id) REFERENCES employes(id),
  CONSTRAINT fk_pointeuse_daily_schedule FOREIGN KEY (schedule_id) REFERENCES pointeuse_work_schedules(id),
  CONSTRAINT fk_pointeuse_daily_approver FOREIGN KEY (approved_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE pointeuse_anomalies (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  employe_id INT NOT NULL,
  work_date DATE NOT NULL,
  daily_summary_id BIGINT NULL,
  anomaly_type ENUM('late','early_leave','missing_in','missing_out','missing_break_end','overlap','outside_schedule','outside_geofence','remote_not_authorized','excessive_duration','insufficient_duration') NOT NULL,
  severity ENUM('info','warning','critical') NOT NULL DEFAULT 'warning',
  status ENUM('detected','to_justify','submitted','approved','rejected','regularized','dismissed') NOT NULL DEFAULT 'detected',
  details_json JSON NULL,
  justification TEXT NULL,
  resolved_by INT NULL,
  resolved_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_pointeuse_anomaly_workflow (status, work_date, severity),
  KEY idx_pointeuse_anomaly_employee (employe_id, work_date),
  CONSTRAINT fk_pointeuse_anomaly_employe FOREIGN KEY (employe_id) REFERENCES employes(id),
  CONSTRAINT fk_pointeuse_anomaly_daily FOREIGN KEY (daily_summary_id) REFERENCES pointeuse_daily_summaries(id),
  CONSTRAINT fk_pointeuse_anomaly_resolver FOREIGN KEY (resolved_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE pointeuse_correction_requests (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  employe_id INT NOT NULL,
  work_date DATE NOT NULL,
  event_id BIGINT NULL,
  requested_event_type ENUM('clock_in','break_start','break_end','clock_out') NULL,
  requested_at_utc DATETIME(3) NULL,
  reason TEXT NOT NULL,
  evidence_url VARCHAR(512) NULL,
  status ENUM('draft','submitted','approved','rejected','applied','cancelled') NOT NULL DEFAULT 'submitted',
  requested_by INT NOT NULL,
  reviewed_by INT NULL,
  review_reason TEXT NULL,
  reviewed_at DATETIME NULL,
  applied_event_id BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_pointeuse_correction_workflow (status, work_date),
  CONSTRAINT fk_pointeuse_correction_employe FOREIGN KEY (employe_id) REFERENCES employes(id),
  CONSTRAINT fk_pointeuse_correction_event FOREIGN KEY (event_id) REFERENCES pointeuse_events(id),
  CONSTRAINT fk_pointeuse_correction_requester FOREIGN KEY (requested_by) REFERENCES users(id),
  CONSTRAINT fk_pointeuse_correction_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id),
  CONSTRAINT fk_pointeuse_correction_applied_event FOREIGN KEY (applied_event_id) REFERENCES pointeuse_events(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE pointeuse_periods (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  date_debut DATE NOT NULL,
  date_fin DATE NOT NULL,
  status ENUM('open','calculated','review','approved','closed','reopened') NOT NULL DEFAULT 'open',
  calc_version VARCHAR(32) NOT NULL DEFAULT 'v3.1',
  calculated_at DATETIME NULL,
  approved_by INT NULL,
  approved_at DATETIME NULL,
  closed_by INT NULL,
  closed_at DATETIME NULL,
  reopened_by INT NULL,
  reopened_at DATETIME NULL,
  reopen_reason TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_pointeuse_period_dates (date_debut, date_fin),
  CONSTRAINT fk_pointeuse_period_approver FOREIGN KEY (approved_by) REFERENCES users(id),
  CONSTRAINT fk_pointeuse_period_closer FOREIGN KEY (closed_by) REFERENCES users(id),
  CONSTRAINT fk_pointeuse_period_reopener FOREIGN KEY (reopened_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
